use_frameworks!

target 'YFPlaceholderView_Example' do
  pod 'YFPlaceholderView', :path => '../'

  target 'YFPlaceholderView_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
