use_frameworks!

target 'YFPlaceholderView_Example' do
  pod 'YFPlaceholderView', :path => '../'
  pod 'Masonry', '~> 1.1.0'
  
  target 'YFPlaceholderView_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
